AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ACMCertArn:
    Type: String
    Description: This is the ACM arn
  SiteURL:
    Type: String
    Description: This is the URL of the site

Outputs:
  HealthCheckId:
    Description: "Physical ID of healthcheck"
    Value: !Ref DestinationHealthCheck
  StandbyReplBucketArn:
    Description: "Full S3 Bucket Arn"
    Value: !Join [ "", [ 'arn:aws:s3:::' , !Ref DestinationReplicationBucket ] ]
Resources:
  DestinationReplicationBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled

  DestinationHealthCheck:
    Type: "AWS::Route53::HealthCheck"
    Properties:
      HealthCheckConfig:
        FullyQualifiedDomainName: !Join [ '.', [ !Join [ '-', [ "s3", !Ref "AWS::Region" ] ], "amazonaws.com" ] ]
        Type: "HTTPS"
        ResourcePath: !Join [ '/', [ '', !Ref 'DestinationReplicationBucket', 'index.html' ] ]
      HealthCheckTags:
        - Key: "Name"
          Value: "DestinationBucketHealthCheck"

  DestinationCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref SiteURL
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: DestinationBucketOrigin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName: !Join [ '.', [ !Ref DestinationReplicationBucket, 's3.amazonaws.com' ] ]
          Id: DestinationBucketOrigin
          S3OriginConfig:
            OriginAccessIdentity: ""
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref ACMCertArn
          SslSupportMethod: sni-only
