AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SiteURL:
    Type: String
    Description: This is the URL of the site
  ZoneName:
    Type: String
    Description: This is the ZoneName of the SiteURL
  AliasTargetDNSName:
    Type: String
    Description: This is the DNS Name of the CloudFront Distro

Outputs:
  StackName:
    Description: This is the StackName
    Value: !Ref 'AWS::StackName'

Resources:
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !Ref AliasTargetDNSName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront zone id hardcoded by design
      HostedZoneName: !Ref ZoneName
      Name: !Ref SiteURL
      Type: A
