AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  PrimaryHealthCheckId:
    Type: String

Outputs:
  PrimaryHealthCheckSNSArn:
    Description: SNS Arn
    Value: !Ref PrimaryHealthCheckSNS
    Export:
      Name: PrimaryHealthCheckSNSArn

Resources:
  PrimaryHealthCheckSNS:
    Type: AWS::SNS::Topic

# NOTE: The alarm MUST be in us-east-1
  PrimaryHealthCheckFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: 'true'
      AlarmActions: [ !Ref PrimaryHealthCheckSNS ]
      AlarmDescription: alarmed when status doesn't respond
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: '1'
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Period: '60'
      Statistic: Minimum
      Threshold: '1.0'
      Dimensions:
      - Name: HealthCheckId
        Value: !Ref PrimaryHealthCheckId
