AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  PrimaryHealthCheckId:
    Type: String
  PrimaryCloudFrontDistributionDomainName:
    Type: String
  HostedZoneName:
    Type: String
  PrimaryUrl:
    Type: String


Outputs:
  PrimaryHealthCheckSNSArn:
    Description: SNS Arn
    Value: !Ref PrimaryHealthCheckSNS
    Export:
      Name: PrimaryHealthCheckSNSArn

Resources:
  PrimaryHealthCheckSNS:
    Type: AWS::SNS::Topic

# NOTE: The alarm MUST be in us-east-1
  PrimaryHealthCheckFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: 'true'
      AlarmActions: [ !Ref PrimaryHealthCheckSNS ]
      AlarmDescription: !Ref PrimaryCloudFrontDistributionDomainName
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: '1'
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Period: '60'
      Statistic: Minimum
      Threshold: '1.0'
      Dimensions:
      - Name: HealthCheckId
        Value: !Ref PrimaryHealthCheckId

  PrimaryHealthCheckFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: main.lambda_handler
      Runtime: python2.7
      CodeUri: ./deployment.zip
      Description: Updates CF distro and Route53
      MemorySize: 128
      Timeout: 10
      Policies:
        - Statement:
            Effect: Allow
            Action: ['route53:ListHostedZonesByName', 'route53:ListResourceRecordSets' ]
            Resource: '*'
      Environment:
        Variables:
          HostedZoneName: !Ref HostedZoneName
          PrimaryUrl: !Ref PrimaryUrl
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref PrimaryHealthCheckSNS
