AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  StandbyHealthCheckId:
    Type: String

Outputs:
  StandbyHealthCheckSNSArn:
    Description: SNS Arn
    Value: !Ref StandbyHealthCheckSNS
    Export:
      Name: StandbyHealthCheckSNSArn

Resources:
  StandbyHealthCheckSNS:
    Type: AWS::SNS::Topic

# NOTE: The alarm MUST be in us-east-1
  StandbyHealthCheckFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: 'true'
      AlarmActions: [ !Ref StandbyHealthCheckSNS ]
      AlarmDescription: alarmed when status doesn't respond
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: '1'
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Period: '60'
      Statistic: Minimum
      Threshold: '1.0'
      Dimensions:
      - Name: HealthCheckId
        Value: !Ref StandbyHealthCheckId

  StandbyHealthCheckFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: main.lambda_handler
      Runtime: python2.7
      CodeUri: ./deployment.zip
      Description: Updates CF distro and Route53
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          R53StackName: "asdf"
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref StandbyHealthCheckSNS
