AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  StandbySiteURL:
    Type: String
    Description: This is the URL of the site
  ZoneName:
    Type: String
    Description: This is the ZoneName of the SiteURL

Resources:
  StandbyDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !ImportValue StandbyCloudFrontDistributionDomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront zone id hardcoded by design
      HostedZoneName: !Ref ZoneName
      Comment: DNS ALIAS for StandbyCloudFrontDistribution
      Name: !Ref StandbySiteURL
      Type: A
