AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  StandbyHealthCheckId:
    Type: String
  PrimaryCloudFrontDistributionDomainName:
    Type: String
  StandbyCloudFrontDistributionDomainName:
    Type: String
  HostedZoneName:
    Type: String
  PrimaryUrl:
    Type: String
  StandbyUrl:
    Type: String

Outputs:
  StandbyHealthCheckSNSArn:
    Description: SNS Arn
    Value: !Ref StandbyHealthCheckSNS
    Export:
      Name: StandbyHealthCheckSNSArn

Resources:
  StandbyHealthCheckSNS:
    Type: AWS::SNS::Topic

# NOTE: The alarm MUST be in us-east-1
  StandbyHealthCheckFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: 'true'
      AlarmActions: [ !Ref StandbyHealthCheckSNS ]
      AlarmDescription: !Ref StandbyCloudFrontDistributionDomainName
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: '1'
      MetricName: HealthCheckStatus
      Namespace: AWS/Route53
      Period: '60'
      Statistic: Minimum
      Threshold: '1.0'
      Dimensions:
      - Name: HealthCheckId
        Value: !Ref StandbyHealthCheckId

  StandbyHealthCheckFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: main.lambda_handler
      Runtime: python2.7
      CodeUri: ./deployment.zip
      Description: Updates CF distro and Route53
      MemorySize: 128
      Timeout: 30
      Policies:
        - Statement:
            Effect: Allow
            Action:
                - 'route53:ChangeResourceRecordSets'
                - 'route53:ListHostedZonesByName'
                - 'route53:ListResourceRecordSets'
            Resource: '*'
        - Statement:
            Effect: Allow
            Action:
                - 'cloudfront:GetDistributionConfig'
                - 'cloudfront:ListDistributions'
                - 'cloudfront:UpdateDistribution'
            Resource: '*'
      Environment:
        Variables:
          HostedZoneName: !Ref HostedZoneName
          PrimaryUrl: !Ref PrimaryUrl
          StandbyUrl: !Ref StandbyUrl
          PrimaryCloudFrontDistributionDomainName: !Ref PrimaryCloudFrontDistributionDomainName
          StandbyCloudFrontDistributionDomainName: !Ref StandbyCloudFrontDistributionDomainName
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref StandbyHealthCheckSNS
